"""remove unique title

Revision ID: a36e8614002f
Revises: 4bb18d0411ea
Create Date: 2023-08-13 19:16:33.904103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36e8614002f'
down_revision: Union[str, None] = '4bb18d0411ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###
