"""add to model Account column confirmed

Revision ID: 504a98ed1f36
Revises: b78e13694580
Create Date: 2023-08-15 17:22:25.145797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504a98ed1f36'
down_revision: Union[str, None] = 'b78e13694580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.alter_column('acc', 'role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acc', 'role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='role'),
               nullable=True)
    op.drop_column('acc', 'confirmed')
    # ### end Alembic commands ###
