"""new

Revision ID: 6985c86cf9c7
Revises: 956026a84877
Create Date: 2023-08-13 18:15:12.029756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6985c86cf9c7'
down_revision: Union[str, None] = '956026a84877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('acc_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'acc', ['acc_id'], ['id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_user_id_fkey', 'users', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'acc_id')
    # ### end Alembic commands ###
