"""add role of user

Revision ID: b78e13694580
Revises: a36e8614002f
Create Date: 2023-08-14 19:58:31.559106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b78e13694580'
down_revision: Union[str, None] = 'a36e8614002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('acc', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    # op.execute("UPDATE acc SET role='user'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acc', 'role')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
